# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""



import os
print(os.listdir())  # Should show the uploaded files

import pandas as pd
df = pd.read_csv("cleaned_dataset.csv")
print(df.head())  # Preview the dataset

from transformers import BartForConditionalGeneration, BartTokenizer

model_name = "sshleifer/distilbart-cnn-6-6"

print("Loading tokenizer...")
tokenizer = BartTokenizer.from_pretrained(model_name)
print("Tokenizer loaded successfully!")

print("Loading model...")
model = BartForConditionalGeneration.from_pretrained(model_name)
print("Model loaded successfully!")

def summarize_text(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=1024)
    summary_ids = model.generate(inputs["input_ids"], max_length=150, min_length=30, length_penalty=2.0)
    return tokenizer.decode(summary_ids[0], skip_special_tokens=True)

sample_chat = "Agent 1: Hello! How can I assist you today? Agent 2: I need help with my account settings."
summary = summarize_text(sample_chat)
print("Chat Summary:", summary)

df.to_csv("your_output_file.csv", index=False)
print("File saved successfully!")

